### ISSUE TITLE
Is "Rewriting request URI in middleware" out of date?

### ISSUE THREAD

**Issue by maxcountryman** [tokio-rs/axum#2575]
I asked about this [in Discord](https://discord.com/channels/500028886025895936/870760546109116496/1204842045890363402) as well, but I'm not sure anyone saw it.

I'm trying to use `NormalizePathLayer` from `tower-http` with `axum` 0.7 as per this [documentation section](https://docs.rs/axum/latest/axum/middleware/index.html#rewriting-request-uri-in-middleware).

For example, I've tried something like this:

```rust
let app: NormalizePath<Router> = NormalizePathLayer::trim_trailing_slash()
     .layer(Router::new().route("/", axum::routing::get(|| async {})));
let listener = tokio::net::TcpListener::bind(addr).await?;
axum::serve(listener, app.into_make_service()).await?;
```

However, the compiler is unhappy about this and complains:

```
error[E0284]: type annotations needed
  --> src/web/app.rs:78:35
   |
78 |         axum::serve(listener, app.into_make_service()).await?;
   |                                   ^^^^^^^^^^^^^^^^^
   |
   = note: cannot satisfy < as HttpBody>::Data == axum::body::Bytes
   = note: required for Router to implement Service<http::Request<>>
   = note: 1 redundant requirement hidden
   = note: required for NormalizePath<Router> to implement Service<http::Request<_>>
note: required by a bound in axum::ServiceExt::into_make_service``
```

Is the documentation current? If so, is this an expected result?

**Comment by robertwayne** [comment]
It looks like using a fully-qualified syntax is the approach to take, see #2377.

I'd agree that the docs should probably be updated to reflect this.

**Comment by maxcountryman** [comment]
Thank you for pointing to that answer, it didn't come up when I searched earlier. The fully-qualified syntax does indeed work.

**Comment by davidpdrsn** [comment]
Yep fully qualified syntax is the way. Its necessary because of how [`Router` implements `Service`](https://github.com/tokio-rs/axum/blob/main/axum/src/routing/mod.rs#L500).

**Comment by maxcountryman** [comment]
@davidpdrsn should the docs be updated then?

Feels like this issue should remain open until then if so.

**Comment by davidpdrsn** [comment]
All examples are checked on CI so it should work.

**Comment by maxcountryman** [comment]
@davidpdrsn I'm confused, the linked note does not mention using the fully qualified syntax, hence this issue being opened in the first place.

That said, the fully qualified syntax does seem to be required (at least to e.g. use `NormalizePathLayer`). 

This seems like an issue that should be addressed in the documentation, no?

**Comment by davidpdrsn** [comment]
The docs don’t mention `NormalizePathLayer` so probably something with how that works that makes rust not able to infer the type. You’re welcome to submit a PR that adds that.

**Comment by wtdcode** [comment]
Documents still not updated at this moment?

https://docs.rs/axum/latest/axum/middleware/index.html#rewriting-request-uri-in-middleware

**Comment by jplatte** [comment]
@wtdcode I'm unclear if there's still a problem now. If there is, could you please open a new issue describing it in a bit more detail?
